### ISSUE TITLE
__repr__ function error

### ISSUE THREAD

**Issue by funatsufumiya** [germaniumhq/mopyx#5]
I tried debug using `MOPYX_DEBUG=1`, this code fired errors (without debug, no error happened.)

```python
@model
class Point:
    def __init__(self, x: float, y: float):
        self.x = x
        self.y = y
    def __repr__(self):
        return f"Point({self.x}, {self.y})"
```

```
Traceback (most recent call last):
  File "index.py", line 51, in <module>
    Point(0.1, 0.1),
  File "xxx/lib/python3.9/site-packages/mopyx/models.py", line 203, in __init__
    super().__init__(*argv, **kw)
  File "index.py", line 42, in __init__
    self.x = x
  File "xxx/lib/python3.9/site-packages/mopyx/models.py", line 25, in action_wrapper
    return f(*args, **kw)
  File "xxx/lib/python3.9/site-packages/mopyx/models.py", line 268, in __setattr__
    print(f"{rendering.indent()}change: {self}.{name} = {value}")
  File "index.py", line 45, in __repr__
    return f"Point({self.x}, {self.y})"
  File "xxx/lib/python3.9/site-packages/mopyx/models.py", line 231, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'ModelProxy' object has no attribute 'y'
```

Probably `__repr__` function must be specified as not action, but how can I achive this?

**Comment by funatsufumiya** [comment]
I noticed I'm using `v1.1.1` (via `pip install mopyx`), I'll retry on master branch later.

**Comment by funatsufumiya** [comment]
on master branch, error message a little bit changed but meanings seems to be the same.

```
Traceback (most recent call last):
  File "index.py", line 45, in <module>
    Point(0.1, 0.1),
  File "xxx/lib/python3.9/site-packages/mopyx/decorator_model.py", line 21, in __init__
    super().__init__(*argv, **kw)
  File "index.py", line 39, in __init__
    self.x = x
  File "xxx/lib/python3.9/site-packages/mopyx/decorator_action.py", line 27, in action_wrapper
    return f(*args, **kw)
  File "xxx/lib/python3.9/site-packages/mopyx/decorator_model.py", line 95, in __setattr__
    print(f"{rendering.indent()}change: {self}.{name} = {value}")
  File "index.py", line 42, in __repr__
    return f"Point({self.x}, {self.y})"
  File "xxx/lib/python3.9/site-packages/mopyx/decorator_model.py", line 49, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'ModelProxy' object has no attribute 'y'
```

And I found that this is not because of action, but `__repr__` is making error.

**Comment by funatsufumiya** [comment]
I found a workaround to fix this bug below:

```python
is_debug = True if os.getenv("MOPYX_DEBUG") else False

@model
class Point:
    def __init__(self, x: float, y: float):
        self.x = x
        self.y = y
    def __repr__(self):
        if is_debug:
            return super().__repr__()
        else:
            return f"Point({self.x}, {self.y})"
```
